### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by Hax0rG1rl** [TypeError/Bookmarks#1]
Hi, 

There is an error message popping up when trying to compile it on a Kali 2019.4 

Steps followed: 

1. apt install gradle

2. git clone https://github.com/TypeError/Bookmarks.git 

3. ./gradlew fatJar

Error: 

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

4. gradle wrapper 

Error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/hunter/Bookmarks/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'bookmarks'.
> Failed to apply plugin [id 'kotlin']
   > Current version of Gradle Gradle 4.4.1 is not compatible with Kotlin plugin. Please use Gradle Gradle 4.9 or newer or previous version of Kotlin plugin.
```

Resource: https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain 

Down to the bottom, I am not a gradle expert but it seems some things are messed around, so, instead of trying to resurrect a dead man here, could you have a releases section for this too where the jar file can be get as standalone jar file.?

Thanks!

Here,

**Comment by cak** [comment]
Thanks for letting me know @Hax0rG1rl! 

I added the gradle wrapper to the repo and updated the installation steps. :) 

I have a couple things to work on this weekend and then I will upload the regular release jar files.

**Comment by cak** [comment]
@Hax0rG1rl You can now find the stand-alone JAR in [releases](https://github.com/TypeError/Bookmarks/releases), thanks!  😄

**Comment by Hax0rG1rl** [comment]
Thank you!
