### ISSUE TITLE
comment field

### ISSUE THREAD

**Issue by theguly** [TypeError/Bookmarks#2]
hi there, do you think it could be possible to add a "note/comment" field? it could be very useful to take notes or quickly remember when/how a particular request has been done.

i totally see why you wrote this extension, because i too often find myself with 20+ repeater tabs opened.

**Comment by cak** [comment]
@theguly, thanks for the feedback! An editable comment field sounds like an excellent idea, and doable - I will put it on the roadmap for a future release.

**Comment by cak** [comment]
@theguly Thanks so much for the suggestion and feedback - I have implemented the ability to add comments (and tags) to the request/response table. Could you please give it a try and provide any feedback (I will be pushing update to the BApp store soon)?

**Comment by theguly** [comment]
sure man, thanks for it.
i'll test as soon as the app reaches bapp store, or do you need a test before?

**Comment by cak** [comment]
@theguly If you could please test with the [latest release](https://github.com/TypeError/Bookmarks/releases/tag/0.4.4) and provide any feedback that would be awesome. I want to make sure I have a polished version before I submit the update to the  BApp Store. 🎉

**Comment by cak** [comment]
@theguly The updated extension is now available in the [BApp Store](https://portswigger.net/bappstore/ef6d970f0d11452ea024691dffb4b39c), please let me know your thoughts!

**Comment by theguly** [comment]
sorry for the delay, i'll test this later today or tomorrow.
thanks a lot for the effort

**Comment by cak** [comment]
@theguly - did you a get a chance to check out the latest version?

**Comment by theguly** [comment]
sorry, looks like i slept to much since last reply :) 
tested but not extensively, will update you within a 2 weeks (this time i promise i will)

**Comment by theguly** [comment]
tested for the last two weeks, all is smooth.
i also appreciated the [^] in repeater's tab name.

thanks for your effort buddy

**Comment by cak** [comment]
Woot! Thanks!
