### ISSUE TITLE
[suggestion] delete clean bookmarks on click-right

### ISSUE THREAD

**Issue by vay3t** [TypeError/Bookmarks#4]
My sugggestion is to delete this option when i access the menu with right-click, to avoid misclicking

![image](https://user-images.githubusercontent.com/6080369/104389545-78da1180-551a-11eb-9648-7525b7855b8d.png)

**Comment by cak** [comment]
Thanks @vay3t 🤩 for bringing this to my attention and agree, we can (and should) remove in favor for the button on my page.

**Comment by cak** [comment]
@vay3t Sorry for the LONG delay on these issues, but I am working on an update!
