### ISSUE TITLE
[suggestion] add names to section of bookmark window - req/resp

### ISSUE THREAD

**Issue by vay3t** [TypeError/Bookmarks#5]
For a matter of formality I recommend adding the name of the bookmark sections for when it is necessary to document. These will be there for greater detail and to be more specific, in order to support the evidence in a more visual and comfortable way.

![image](https://user-images.githubusercontent.com/6080369/104508651-518d4e00-55c7-11eb-981c-e4e31ae09cb7.png)

like a repeater:
![image](https://user-images.githubusercontent.com/6080369/104508810-88636400-55c7-11eb-9fa9-4b2b25917881.png)

**Comment by cak** [comment]
Thanks @vay3t! Great suggestion, I will get this added for the next release. 🥳
